spring:
  profiles:
    include:
      - secret
      - db

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger

file:
  upload-dir: uploads

streaming:
  rtmp-url: rtmp://localhost:1935/live
  hls-url: http://localhost:8081/hls
  server-url: http://localhost:8081